config/routes.rb
Thot::Application.routes.draw do

  resources :books, :only => [:index, :show]
  resources :items, :only=>[:show]
  resources :loans, :only => [:create, :destroy]
  resources :publishers, :only => [:show]
  resources :searches
  resources :shelves, :only => [:show] do
    resources :items, :only => [:index]
  end

  resources :users, :only => [:show, :index]
  namespace :nebis do
    get 'extend'
  end
  resources :nebis, :only => [:show]

  devise_for :admins
  namespace :adm do
    resources :admins do
      get :reset_password
    end
    resources :books do
      get :autocomplete_publisher_name, :on => :collection
      get :duplicate
      resources :items, :only=>[:new, :create]
    end
    resources :deg_isbns do
      get :skip, :on => :member
    end
    resources :goods
    resources :inventory_sessions do
      resources :shelves, :only => [:show]
      post :check
      post :uncheck
      get  :commit_moves
      get  :commit_missings
    end
    match 'inventory_sessions/inventorize_search', :to => 'inventory_sessions#inventorize_search', :via => :post, :as => 'inventorize_search'
    resources :items, :only=>[:index, :show, :edit, :update, :destroy]
    resources :labs
    resources :locations do
      resources :shelves, :only=>[:new, :create, :index]
    end
    resources :label_layouts
    resources :publishers, :only => [:index, :new, :edit, :create, :update, :destroy]
    resources :publisher_mergers, :only=>[:new, :create, :update]
    resources :shelves, :only => [:index, :show, :update, :destroy]
    resources :users do
    end
  end

  root :to => "searches#new"

end

app/models/adm.rb
module Adm
  def self.table_name_prefix
    'adm_'
  end
end

app/controllers/adm/admins_controller.rb
class Adm::AdminsController < AdmController
  before_action :administrator_only!

  # GET /adm/admins
  # GET /adm/admins.json
  def index
    @admins = Admin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admins }
    end
  end

  # GET /adm/admins/1
  # GET /adm/admins/1.json
  def show
    @admin = Admin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin }
    end
  end

  # GET /adm/admins/new
  # GET /adm/admins/new.json
  def new
    @admin = Admin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin }
    end
  end

  # GET /adm/admins/1/edit
  def edit
    @admin = Admin.find(params[:id])
  end

  # POST /adm/admins
  # POST /adm/admins.json
  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        format.html { redirect_to [:adm, @admin], notice: 'Admin was successfully created.' }
        format.json { render json: @admin, status: :created, location: @admin }
      else
        format.html { render action: "new" }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /adm/admins/1
  # PUT /adm/admins/1.json
  def update
    @admin = Admin.find(params[:id])

    respond_to do |format|
      if @admin.update_attributes(admin_params)
        format.html { redirect_to [:adm, @admin], notice: 'Admin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adm/admins/1
  # DELETE /adm/admins/1.json
  def destroy
    @admin = Admin.find(params[:id])
    @admin.destroy

    respond_to do |format|
      format.html { redirect_to adm_admins_url }
      format.json { head :no_content }
    end
  end

  # GET /adm/admins/1/reset_password
  def reset_password
    @admin = Admin.find(params[:admin_id])
    @admin.send_welcome_email
    redirect_to [:adm, @admin], notice: "Reset password email was sent to #{@admin.name}"
  end
 private

  def admin_params
    params.require(:admin).permit :name, :email, :role, :password, :password_confirmation, :remember_me, :lab_ids => []
  end

end

app/controllers/adm/books_controller.rb
class Adm::BooksController < AdmController
  # TODO: re-enable autocomplete when a rails4 compatible version is out
  # autocomplete :publisher, :name, :full => true


  # GET /adm/books
  def index
    @books = (
      case params[:with]
      when 'badISBN'
        @subtitle = "With bad ISBN numbers"
        Book.where('isbn IS NOT NULL AND length(isbn) != 13 AND length(isbn) != 10')
      else
        Book.order('updated_at DESC')
      end
    ).paginate(:page=>params[:page], :per_page=>50)
    respond_to do |format|
      format.html { render 'books/index' }
    end
  end

  # GET /adm/books/new
  def new
    @isbn_step = true
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /adm/books/id
  def duplicate
    original = Book.find(params[:book_id])
    @book = original.duplicate
    respond_to do |format|
      format.html
    end
  end

  # GET /adm/books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /adm/books
  def create
    if params[:isbn_step]
      @books=Book.new_given_isbn(book_params[:isbn])
      if @books.count == 1
        @book=@books.first
        if @book.new_record?
          # @labs = Lab.order('nick ASC').all
          # @locations = Location.order('name ASC').all
          # @currencies = ENV['CURRENCIES'].split
          # @item = Item.new
          @isbn_step = false
          render "new"
        else
          flash[:notice] = "A book with the same ISBN number was found on our database. Please review the data or click on duplicate to add a different volume or edition."
          render "edit"
        end
      else
        if @books.first.new_record?
          @book = Book.new(book_params)
          render "new_as_merge"
        else
          @isbn = params[:book][:isbn]
          @deg_isbn = DegIsbn.where(:isbn => @isbn).first
          flash[:notice] = "Degenerate ISBN"
          # render "books/index" #, :collection => @books
          # # render "index"
        end
      end
    else
      @book = Book.new(book_params)

      respond_to do |format|
        if @book.save
          format.html { redirect_to new_adm_book_item_path(@book), notice: 'Book was successfully created.' }
        else
          format.html { render action: "new" }
        end
      end
    end
  end

  # PUT /adm/books/1
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /adm/books/1
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
    end
  end

 private

  def book_params
    params.require(:book).permit :abstract, :author, :call1, :call2, :call3, :call4, :categories, :collation, :collection, :currency, :edition, :editor, :idx, :isbn, :language, :notes, :price, :pubyear, :title, :toc, :publisher_name, :subtitle, :volume
  end

end

app/controllers/adm/deg_isbns_controller.rb
class Adm::DegIsbnsController < AdmController
  def index
    @degisbns=DegIsbn.paginate(:page=>params[:page], :per_page=>200)
  end

  # GET /isbn_dedup/1
  def show
    @degisbn=DegIsbn.find(params["id"])
    set_prev_next
    set_books
  end

  # GET /isbn_dedup/1/edit
  def edit
    @degisbn=DegIsbn.find(params["id"])
    set_prev_next_editable
    set_books
  end

  # GET /isbn_dedup/1/skip
  def skip
    skippand=DegIsbn.find(params["id"])
    skippand.skip=true
    skippand.save
    @degisbn=DegIsbn.editable.where("id > #{skippand.id}").first
    set_prev_next_editable
    set_books
    flash[:notice] = "Degenerate ISBN #{skippand.isbn} marked as unmergeable"
    render action: "edit"
  end

  # TODO: prevent multiple users from merging the same isbn
  def update
    @degisbn=DegIsbn.find(params["id"])
    isbn=@degisbn.isbn
    @book=Book.new(book_params)
    @book.isbn=isbn
    if @book.save
      @degisbn.count = @degisbn.count + 1
      @degisbn.books.find(params["merge_book_ids"]).each do |b|
        b.items.each do |i|
          @book.items << i
        end
        b.destroy
        @degisbn.count = @degisbn.count - 1
      end
      @degisbn.save
      if @degisbn.count==1
        myid=@degisbn.id
        @degisbn.destroy
        @degisbn=DegIsbn.editable.where("id > #{myid}").first
        set_prev_next_editable
        set_books
        flash[:notice] = "Isbn #{isbn} is no longer degenerate. Thank you!"
        render :action => :edit
      else
        set_prev_next_editable
        set_books
        flash[:notice] = "Still some degenerate books with ISBN #{isbn}"
        render :action => "edit"
      end
    else
      render :action => "edit"
    end
  end

 private

  def book_params
    params.require(:book).permit :abstract, :author, :call1, :call2, :call3, :call4, :categories, :collation, :collection, :currency, :edition, :editor, :idx, :isbn, :language, :notes, :price, :pubyear, :title, :toc, :publisher_name, :subtitle, :volume
  end

  def set_prev_next_editable
    @prev = DegIsbn.editable.where("id < #{@degisbn.id}").last
    @next = DegIsbn.editable.where("id > #{@degisbn.id}").first
  end

  def set_prev_next
    @prev = DegIsbn.where("id < #{@degisbn.id}").last
    @next = DegIsbn.where("id > #{@degisbn.id}").first
  end

  def set_books
    @books=@degisbn.books
    @book=Book.new
  end
end

app/controllers/adm/goods_controller.rb
class Adm::GoodsController < AdmController

  # POST /adm/goods
  def create
    @location = Location.find(params[:location_id])
    @shelf =  @location.shelves.new
    respond_to do |format|
      if @shelf.save
        format.html { redirect_to @location, notice: 'Shelf added.' }
        format.js { render js: "thot.increase_counter('#shc_#{@location.id}');" }
      else
        format.html { render action: "new" }
        format.json { render json: @lab.errors, status: :unprocessable_entity }
      end
    end
  end

  # # GET /adm/goods/:id/uncheck
  # def uncheck
  #   @good = Good.find(:id)
  #   respond_to do |format|
  #     if can? :update, @good
  #       @good.current_shelf=nil
  #       respond_to do |format|
  #         format.js
  #       end
  #     else
  #       respond_to do |format|
  #         format.js {  render :js => "window.location = '/'", :status => :unauthorized }
  #       end
  #     end
  #   end
  # end

  # # GET /adm/inventory_sessions/:inventory_session_id/:inv/edit
  # def edit
  #   @inventory_session = inventorySession.find(params[:inventory_session])
  #   @good = @inventory_session.goods.where(:inv=>params[:id])
  #   respond_to do |format|
  #     format.js
  #   end
  # end

  # def update
  # end
end

app/controllers/adm/items_controller.rb
class Adm::ItemsController < AdmController
  before_action :set_book, :only => [:new, :create]
  # cancan::load_and_authorize_resource incompatible with strong params
  # load_and_authorize_resource :except => [:index]

  # GET /items
  # GET /items.json
  def index
    @labs = current_admin.labs
    if current_admin.admin? && ( @labs.empty? || params[:all] )
      @items = Item.order("created_at DESC").paginate(:page=>params[:page], :per_page=>50)
      @link_to_my = ! @labs.empty?
      @link_to_all = false
    else
      @link_to_all = current_admin.admin?
      @link_to_my = false
      @items = Item.where(:lab_id => @labs).order("created_at DESC").paginate(:page=>params[:page], :per_page=>50)
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
    @book = @item.book
    respond_to do |format|
      format.html { render 'items/show' }
      format.pdf  { @items = [@item] ; render 'items/index' }
      format.json { render json: @item }
    end
  end

  # GET /book/:book_id/items/new
  # GET /book/:book_id/items/new.json
  def new
    @item = @book.items.new
    set_form_data
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
    set_form_data
  end

  # POST /book/:book_id/items
  # POST /book/:book_id//items.json
  def create
    @book = Book.find(params[:book_id])
    if @book
      @item = @book.items.new(item_params)
      authorize! :create, @item
      respond_to do |format|
        if @item.save
          format.html { redirect_to @book, notice: 'Item was successfully created.' }
          format.json { render json: @item, status: :created, location: @item }
        else
          format.html {
            set_form_data
            render action: "new"
          }
          format.json { render json: @item.errors, status: :unprocessable_entity }
        end
      end
    else

    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])
    authorize! :update, @item

    respond_to do |format|
      if @item.update_attributes(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html {
          set_form_data
          render action: "edit"
        }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    authorize! :destroy, @item
    @item.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

 private
  def set_book
    if params.has_key?(:book_id) && @book = Book.find(params[:book_id])
      true
    else
      false
    end
  end

  def item_params
    @item_params ||= params.require(:item).permit(:currency, :lab_id, :shelf_id, :location_name, :location_id, :price, :status)
  end

  def set_form_data
    @locations = Location.order('name ASC').all
    @currencies = ENV['CURRENCIES'].split
    @labs = current_admin.available_labs
    if @labs.empty? && current_admin.admin?
      @labs = Lab.all
    end
  end

end

app/controllers/adm/label_layouts_controller.rb
class Adm::LabelLayoutsController < AdmController

   respond_to :html

  # GET /admin/label_layouts
  def index
    @label_layouts = LabelLayout.all
    respond_with @label_layouts
  end

  # GET /admin/label_layouts/1
  def show
    @label_layout = LabelLayout.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf
    end
  end

  # GET /admin/label_layouts/new
  def new
    authorize! :create, LabelLayout
    @label_layout = LabelLayout.new
    respond_with @label_layout
  end

  # GET /admin/label_layouts/1/edit
  def edit
    @label_layout = LabelLayout.find(params[:id])
    authorize! :update, @label_layout
    respond_with @label_layout
  end

  # POST /admin/label_layouts
  def create
    @label_layout = LabelLayout.new(label_layout_params)
    authorize! :create, @label_layout
    respond_to do |format|
      if @label_layout.save
        format.html { redirect_to [:adm, @label_layout], notice: 'LabelLayout was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /admin/label_layouts/1
  # PUT /admin/label_layouts/1.json
  def update
    @label_layout = LabelLayout.find(params[:id])
    authorize! :update, @label_layout

    respond_to do |format|
      if @label_layout.update_attributes(label_layout_params)
        format.html { redirect_to [:adm, @label_layout], notice: 'LabelLayout was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /admin/label_layouts/1
  def destroy
    @label_layout = LabelLayout.find(params[:id])
    authorize! :destroy, @label_layout

    respond_to do |format|
      if @label_layout.destroy
        format.html { redirect_to adm_label_layouts_url, notice: "LabelLayout #{@label_layout.name} destroyed." }
      else
        format.html { redirect_to [:adm, @label_layout], notice: 'Could not destroy label layout' }
      end
    end
  end

 private

  def label_layout_params
    params.require(:label_layout).permit(:name, :description, :pw, :ph, :mt, :mr, :mb, :ml, :nr, :nc, :vs, :hs, :vp, :hp, :page)
  end

end

app/controllers/adm_controller.rb
class AdmController < ApplicationController
  before_action :authenticate_admin!

  def administrator_only!
    # raise User::NotAuthorized unless current_user.admin?
    if current_admin.admin?
      true
    else
      user_not_authorized
      false
    end
  end

end

app/helpers/adm/admins_helper.rb
module Adm::AdminsHelper
end

app/helpers/adm/books_helper.rb
module Adm::BooksHelper
end

app/helpers/adm/inventory_sessions_helper.rb
module Adm::InventorySessionsHelper
end

app/helpers/adm/labs_helper.rb
module Adm::LabsHelper
end

app/helpers/adm/locations_helper.rb
module Adm::LocationsHelper
end

app/views/adm/publisher_mergers/edit.html.haml
-content_for(:title) do
  DB Cleanup:
  %small merge publishers


= simple_form_for([:adm, @publisher], :url=>adm_publisher_mergers_path, :method => :post) do |f|
  %row
    .span6
      -#= f.input "mergenda_ids", :as=>:check_boxes, :collection=>@publishers
      %ul.unstyled
        -@publishers.each do |p|
          %li
            %i.icon-minus-sign.remove_from_list
            %input{:name=>"mergenda_ids[]", :type=>"hidden", :value=>p.id}
            =p.name
    .span4
      %p
        Are you sure that you want to
        %strong replace
        all the publishers listed here with a new one having the name below ?
      .form-inputs
        = f.input :name, :label => "New name"
      .form-actions
        = f.button :submit, "Yes I am sure. Please merge them!"

-#content_for :head do
  :css
    .remove_from_list:hover {border: 1px solid #f00;}
    #selectable .ui-selecting { background: #FECA40; }
    #selectable .ui-selected { background: #F39814; color: white; }
  :javascript
    jQuery(document).ready(function($) {
      $("#selectable").selectable({
        stop: function() {
          $(".ui-widget-content input").prop('checked', false);
          $(".ui-selected input").prop('checked', true);
        }
      });
    });

app/views/adm/publisher_mergers/index.html.haml
%h1 Listing publisher_mergers

%table
  %tr
    %th New
    %th Create
    %th Edit
    %th Update
    %th
    %th
    %th

  - @publisher_mergers.each do |publisher_merger|
    %tr
      %td= publisher_merger.new
      %td= publisher_merger.create
      %td= publisher_merger.edit
      %td= publisher_merger.update
      %td= link_to 'Show', publisher_merger
      %td= link_to 'Edit', edit_publisher_merger_path(publisher_merger)
      %td= link_to 'Destroy', publisher_merger, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Publisher merger', new_publisher_merger_path

app/views/adm/publisher_mergers/new.html.haml
-content_for(:title) do
  DB Cleanup:
  %small merge publishers

= simple_form_for([:adm, @publisher], :url=>adm_publisher_mergers_path, :method => :post) do |f|
  %row
    .span6
      -#= f.input "mergenda_ids", :as=>:check_boxes, :collection=>@publishers
      %ul#selectable.unstyled
        -@publishers.each do |p|
          %li.ui-widget-content
            %label.checkbox
              %input{:name=>"mergenda_ids[]", :type=>"checkbox", :value=>p.id, :checked=>false, :class=>"ui-widget-content"}= p.name

    .span4
      %p
        Select the publisher's names that you want to merge and enter here the
        new name for the new publisher that will replace those that you have selected.
        You can also avoid typing by choising one of the names proposed in the selector below.
        Field can be edited in any case.
      .form-inputs
        = f.input :name, :label => "New name", :input_html=>{:class=>'span4'}
        %select#selectedselector
          %option uno
          %option due
      .form-actions
        = f.button :submit, "Merge"

-content_for :head do
  :javascript
    function when_ready_for_view() {
      thot.selectable_merger();
      // $("#selectedselector").hide();
      // $("#selectedselector").change(function(){
      //   console.debug("cambiato selettore");
      //   $("#publisher_name").val($(this).val());
      // });
      // $("#selectable").selectable({
      //   stop: function() {
      //     var choices=[];
      //     $(".ui-widget-content input").prop('checked', false);
      //     $(".ui-selected input").prop('checked', true);
      //     var options=$("#selectedselector");
      //     $("#publisher_name").val("");
      //     options.empty();
      //     $(".ui-selected label").each(function(index) {
      //       var v=$(this).text().trim();
      //       options.append($("<option></option>").attr("value", v).text(v));
      //     });
      //     options.show();
      //   }
      // });
      // // $(.publisher_name).doubleclick(function() {
      // //   alert('Double cliccked');
      // // });
    }

app/views/adm/publisher_mergers/show.html.haml
%p#notice= notice

%p
  %b New:
  = @publisher_merger.new
%p
  %b Create:
  = @publisher_merger.create
%p
  %b Edit:
  = @publisher_merger.edit
%p
  %b Update:
  = @publisher_merger.update

= link_to 'Edit', edit_publisher_merger_path(@publisher_merger)
\|
= link_to 'Back', publisher_mergers_path