config/routes.rb
Thot::Application.routes.draw do

  resources :books, :only => [:index, :show]
  resources :items, :only=>[:show]
  resources :loans, :only => [:create, :destroy]
  resources :publishers, :only => [:show]
  resources :searches
  resources :shelves, :only => [:show] do
    resources :items, :only => [:index]
  end

  resources :users, :only => [:show, :index]
  namespace :nebis do
    get 'extend'
  end
  resources :nebis, :only => [:show]

  devise_for :admins
  namespace :adm do
    resources :admins do
      get :reset_password
    end
    resources :books do
      get :autocomplete_publisher_name, :on => :collection
      get :duplicate
      resources :items, :only=>[:new, :create]
    end
    resources :deg_isbns do
      get :skip, :on => :member
    end
    resources :goods
    resources :inventory_sessions do
      resources :shelves, :only => [:show]
      post :check
      post :uncheck
      get  :commit_moves
      get  :commit_missings
    end
    match 'inventory_sessions/inventorize_search', :to => 'inventory_sessions#inventorize_search', :via => :post, :as => 'inventorize_search'
    resources :items, :only=>[:index, :show, :edit, :update, :destroy]
    resources :labs
    resources :locations do
      resources :shelves, :only=>[:new, :create, :index]
    end
    resources :label_layouts
    resources :publishers, :only => [:index, :new, :edit, :create, :update, :destroy]
    resources :publisher_mergers, :only=>[:new, :create, :update]
    resources :shelves, :only => [:index, :show, :update, :destroy]
    resources :users do
    end
  end

  root :to => "searches#new"

end

app/controllers/adm/admins_controller.rb
class Adm::AdminsController < AdmController
  before_action :administrator_only!

  # GET /adm/admins
  # GET /adm/admins.json
  def index
    @admins = Admin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admins }
    end
  end

  # GET /adm/admins/1
  # GET /adm/admins/1.json
  def show
    @admin = Admin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin }
    end
  end

  # GET /adm/admins/new
  # GET /adm/admins/new.json
  def new
    @admin = Admin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin }
    end
  end

  # GET /adm/admins/1/edit
  def edit
    @admin = Admin.find(params[:id])
  end

  # POST /adm/admins
  # POST /adm/admins.json
  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        format.html { redirect_to [:adm, @admin], notice: 'Admin was successfully created.' }
        format.json { render json: @admin, status: :created, location: @admin }
      else
        format.html { render action: "new" }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /adm/admins/1
  # PUT /adm/admins/1.json
  def update
    @admin = Admin.find(params[:id])

    respond_to do |format|
      if @admin.update_attributes(admin_params)
        format.html { redirect_to [:adm, @admin], notice: 'Admin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adm/admins/1
  # DELETE /adm/admins/1.json
  def destroy
    @admin = Admin.find(params[:id])
    @admin.destroy

    respond_to do |format|
      format.html { redirect_to adm_admins_url }
      format.json { head :no_content }
    end
  end

  # GET /adm/admins/1/reset_password
  def reset_password
    @admin = Admin.find(params[:admin_id])
    @admin.send_welcome_email
    redirect_to [:adm, @admin], notice: "Reset password email was sent to #{@admin.name}"
  end
 private

  def admin_params
    params.require(:admin).permit :name, :email, :role, :password, :password_confirmation, :remember_me, :lab_ids => []
  end

end

app/controllers/adm/books_controller.rb
class Adm::BooksController < AdmController
  # TODO: re-enable autocomplete when a rails4 compatible version is out
  # autocomplete :publisher, :name, :full => true


  # GET /adm/books
  def index
    @books = (
      case params[:with]
      when 'badISBN'
        @subtitle = "With bad ISBN numbers"
        Book.where('isbn IS NOT NULL AND length(isbn) != 13 AND length(isbn) != 10')
      else
        Book.order('updated_at DESC')
      end
    ).paginate(:page=>params[:page], :per_page=>50)
    respond_to do |format|
      format.html { render 'books/index' }
    end
  end

  # GET /adm/books/new
  def new
    @isbn_step = true
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /adm/books/id
  def duplicate
    original = Book.find(params[:book_id])
    @book = original.duplicate
    respond_to do |format|
      format.html
    end
  end

  # GET /adm/books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /adm/books
  def create
    if params[:isbn_step]
      @books=Book.new_given_isbn(book_params[:isbn])
      if @books.count == 1
        @book=@books.first
        if @book.new_record?
          # @labs = Lab.order('nick ASC').all
          # @locations = Location.order('name ASC').all
          # @currencies = ENV['CURRENCIES'].split
          # @item = Item.new
          @isbn_step = false
          render "new"
        else
          flash[:notice] = "A book with the same ISBN number was found on our database. Please review the data or click on duplicate to add a different volume or edition."
          render "edit"
        end
      else
        if @books.first.new_record?
          @book = Book.new(book_params)
          render "new_as_merge"
        else
          @isbn = params[:book][:isbn]
          @deg_isbn = DegIsbn.where(:isbn => @isbn).first
          flash[:notice] = "Degenerate ISBN"
          # render "books/index" #, :collection => @books
          # # render "index"
        end
      end
    else
      @book = Book.new(book_params)

      respond_to do |format|
        if @book.save
          format.html { redirect_to new_adm_book_item_path(@book), notice: 'Book was successfully created.' }
        else
          format.html { render action: "new" }
        end
      end
    end
  end

  # PUT /adm/books/1
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /adm/books/1
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
    end
  end

 private

  def book_params
    params.require(:book).permit :abstract, :author, :call1, :call2, :call3, :call4, :categories, :collation, :collection, :currency, :edition, :editor, :idx, :isbn, :language, :notes, :price, :pubyear, :title, :toc, :publisher_name, :subtitle, :volume
  end

end

app/controllers/adm/deg_isbns_controller.rb
class Adm::DegIsbnsController < AdmController
  def index
    @degisbns=DegIsbn.paginate(:page=>params[:page], :per_page=>200)
  end

  # GET /isbn_dedup/1
  def show
    @degisbn=DegIsbn.find(params["id"])
    set_prev_next
    set_books
  end

  # GET /isbn_dedup/1/edit
  def edit
    @degisbn=DegIsbn.find(params["id"])
    set_prev_next_editable
    set_books
  end

  # GET /isbn_dedup/1/skip
  def skip
    skippand=DegIsbn.find(params["id"])
    skippand.skip=true
    skippand.save
    @degisbn=DegIsbn.editable.where("id > #{skippand.id}").first
    set_prev_next_editable
    set_books
    flash[:notice] = "Degenerate ISBN #{skippand.isbn} marked as unmergeable"
    render action: "edit"
  end

  # TODO: prevent multiple users from merging the same isbn
  def update
    @degisbn=DegIsbn.find(params["id"])
    isbn=@degisbn.isbn
    @book=Book.new(book_params)
    @book.isbn=isbn
    if @book.save
      @degisbn.count = @degisbn.count + 1
      @degisbn.books.find(params["merge_book_ids"]).each do |b|
        b.items.each do |i|
          @book.items << i
        end
        b.destroy
        @degisbn.count = @degisbn.count - 1
      end
      @degisbn.save
      if @degisbn.count==1
        myid=@degisbn.id
        @degisbn.destroy
        @degisbn=DegIsbn.editable.where("id > #{myid}").first
        set_prev_next_editable
        set_books
        flash[:notice] = "Isbn #{isbn} is no longer degenerate. Thank you!"
        render :action => :edit
      else
        set_prev_next_editable
        set_books
        flash[:notice] = "Still some degenerate books with ISBN #{isbn}"
        render :action => "edit"
      end
    else
      render :action => "edit"
    end
  end

 private

  def book_params
    params.require(:book).permit :abstract, :author, :call1, :call2, :call3, :call4, :categories, :collation, :collection, :currency, :edition, :editor, :idx, :isbn, :language, :notes, :price, :pubyear, :title, :toc, :publisher_name, :subtitle, :volume
  end

  def set_prev_next_editable
    @prev = DegIsbn.editable.where("id < #{@degisbn.id}").last
    @next = DegIsbn.editable.where("id > #{@degisbn.id}").first
  end

  def set_prev_next
    @prev = DegIsbn.where("id < #{@degisbn.id}").last
    @next = DegIsbn.where("id > #{@degisbn.id}").first
  end

  def set_books
    @books=@degisbn.books
    @book=Book.new
  end
end

app/controllers/adm/goods_controller.rb
class Adm::GoodsController < AdmController

  # POST /adm/goods
  def create
    @location = Location.find(params[:location_id])
    @shelf =  @location.shelves.new
    respond_to do |format|
      if @shelf.save
        format.html { redirect_to @location, notice: 'Shelf added.' }
        format.js { render js: "thot.increase_counter('#shc_#{@location.id}');" }
      else
        format.html { render action: "new" }
        format.json { render json: @lab.errors, status: :unprocessable_entity }
      end
    end
  end

  # # GET /adm/goods/:id/uncheck
  # def uncheck
  #   @good = Good.find(:id)
  #   respond_to do |format|
  #     if can? :update, @good
  #       @good.current_shelf=nil
  #       respond_to do |format|
  #         format.js
  #       end
  #     else
  #       respond_to do |format|
  #         format.js {  render :js => "window.location = '/'", :status => :unauthorized }
  #       end
  #     end
  #   end
  # end

  # # GET /adm/inventory_sessions/:inventory_session_id/:inv/edit
  # def edit
  #   @inventory_session = inventorySession.find(params[:inventory_session])
  #   @good = @inventory_session.goods.where(:inv=>params[:id])
  #   respond_to do |format|
  #     format.js
  #   end
  # end

  # def update
  # end
end

app/controllers/adm/inventory_sessions_controller.rb
class Adm::InventorySessionsController < AdmController

  # POST /adm/inventory_sessions/inventorize_search
  def inventorize_search
    isid = params["inventorize"]["session_id"]
    puts "--------- isid=#{isid}   blank? #{isid.blank?}   nil? #{isid.nil?}"
    search = Search.find(params["inventorize"]["search_id"])
    if isid.nil? || isid.blank?
      redirect_to search, :notice => "Please select and inventory session"
    else
      @inventory_session = InventorySession.find(params["inventorize"]["session_id"])
      @inventory_session.inventorize_search(search)
      redirect_to [:adm, @inventory_session]
    end
  end

  # POST /adm/inventory_sessions/:id/check/:inv
  def check
    @inventory_session = InventorySession.find(params[:inventory_session_id])
    @shelf = Shelf.find(params[:shelf])
    @good = @inventory_session.goods.where(item_id: params[:inv]).first
    respond_to do |format|
      if @good
        @good.update_attribute(:current_shelf_id, @shelf.id)
        format.json { render json: { good: @good, status: @good.status(@shelf.id), id: "inv_#{@good.inv}", li: render_to_string(:partial => 'adm/goods/good', :layout => false, :formats => [:html], :locals => { :good => @good }) } }
      else
        format.json { render json: { good: false, message: "The item you have scanned is not among the goods of this inventory session"}, status: :not_found }
      end
    end
  end

  def uncheck
    @inventory_session = InventorySession.find(params[:inventory_session_id])
    @shelf = Shelf.find(params[:shelf])
    @good = @inventory_session.goods.where(item_id: params[:inv]).first
    respond_to do |format|
      if @good
        @good.update_attribute(:current_shelf_id, nil)
        format.json { render json: { good: @good, status: @good.status(@shelf.id), id: "inv_#{@good.inv}", li: render_to_string(:partial => 'adm/goods/good', :layout => false, :formats => [:html], :locals => { :good => @good }) } }
      else
        format.json { render json: { good: false, message: "Not Found :("}, status: :not_found }
      end
    end
  end

  # GET /adm/inventory_sessions/:id/commit_moves
  def commit_moves
    @inventory_session = InventorySession.find(params[:inventory_session_id])
    n = @inventory_session.commit_moves
    respond_to do |format|
      format.html { redirect_to [:adm, @inventory_session], :notice => "#{n} moves committed." }
    end
  end

  # GET /adm/inventory_sessions/:id/commit_missings
  def commit_missings
    @inventory_session = InventorySession.find(params[:inventory_session_id])
    n = @inventory_session.commit_missings
    respond_to do |format|
      format.html { redirect_to [:adm, @inventory_session], :notice => "#{n} missing committed." }
    end
  end

  # GET /adm/inventory_sessions
  # GET /adm/inventory_sessions.json
  def index
    if current_admin.admin? and not params[:mine_only]
      @all = true
      @inventory_sessions = InventorySession.all
    else
      @all = false
      @inventory_sessions = current_admin.inventory_sessions
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @inventory_sessions }
    end
  end

  # GET /adm/inventory_sessions/1
  # GET /adm/inventory_sessions/1.json
  def show
    @inventory_session = InventorySession.find(params[:id])
    @shelves = @inventory_session.shelves
    gon.inventory = @inventory_session.id
    respond_to do |format|
      format.pdf do
        @items = @inventory_session.items.includes(:inventoriable, :shelf).order(:shelf_id).sort do |a,b|
          if a.shelf_id == b.shelf_id
            begin
              if a.inventoriable.is_a?(Book) && b.inventoriable.is_a?(Book)
                a.inventoriable.sortable_call <=> b.inventoriable.sortable_call
              else
                a.id <=> b.id
              end
            rescue
              a.id <=> b.id
            end
          else
            a.shelf ? a.shelf.seqno : 0  <=> b.shelf ? b.shelf.seqno : 0
          end
        end
      end
      format.html # show.html.erb
      format.json { render json: @inventory_session }
      format.csv do
        @records = [["Inv", "Lab", "Call1", "Call2", "Call3", "Title"]]
        @records += @inventory_session.books_by_call_for_listing.map{|r| [r.id, r.lab_nick, r.call1, r.call2, r.call3, r.title]}
        send_data CSV.generate {|csv| @records.each {|r| csv << r} }
      end
      format.xls # renders show.xls.erb
      # format.xls {
      #   @records = [["Inv", "Lab", "Call1", "Call2", "Call3", "Title"]]
      #   @records += @inventory_session.books_by_call_for_listing.map{|r| [r.id, r.lab_nick, r.call1, r.call2, r.call3, r.title]}
      #   send_data CSV.generate(col_sep: "\t") {|csv| @records.each {|r| csv << r} }
      # }
    end
  end

  # GET /adm/inventory_sessions/new
  # GET /adm/inventory_sessions/new.json
  def new
    @inventory_session = InventorySession.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @inventory_session }
    end
  end

  # GET /adm/inventory_sessions/1/edit
  def edit
    @inventory_session = InventorySession.find(params[:id])
  end

  # POST /adm/inventory_sessions
  # POST /adm/inventory_sessions.json
  def create
    @inventory_session = InventorySession.new(inventory_session_params)
    @inventory_session.admin ||= current_admin
    respond_to do |format|
      if @inventory_session.save
        format.html { redirect_to [:adm, @inventory_session], notice: 'Inventory session was successfully created.' }
        format.json { render json: @inventory_session, status: :created, location: @inventory_session }
      else
        format.html { render action: "new" }
        format.json { render json: @inventory_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /adm/inventory_sessions/1
  # PUT /adm/inventory_sessions/1.json
  def update
    @inventory_session = InventorySession.find(params[:id])

    respond_to do |format|
      if @inventory_session.update_attributes(inventory_session_params)
        format.html { redirect_to [:adm, @inventory_session], notice: 'Inventory session was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @inventory_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adm/inventory_sessions/1
  # DELETE /adm/inventory_sessions/1.json
  def destroy
    @inventory_session = InventorySession.find(params[:id])
    @inventory_session.destroy

    respond_to do |format|
      format.html { redirect_to adm_inventory_sessions_url }
      format.json { head :no_content }
    end
  end

 private

  def inventory_session_params
    params.require(:inventory_session).permit(:name, :notes)
  end
end

app/helpers/adm/admins_helper.rb
module Adm::AdminsHelper
end

app/helpers/adm/books_helper.rb
module Adm::BooksHelper
end

app/views/adm/books/_form.html.haml
= simple_form_for([:adm, @book]) do |f|
  = f.error_notification

  .form-inputs
    - if @isbn_step
      = hidden_field_tag 'isbn_step', true
      = f.input :isbn
    - else
      = f.input :isbn, :as => :hidden
      = f.input :author, :input_html=>{:class => "span10"}
      = f.input :title, :input_html=>{:class => "span10"}
      = f.input :subtitle , :input_html=>{:class => "span10"}
      = f.input :editor, :input_html=>{:class => "span10"}
      .row
        .span1= f.input :volume, :input_html=>{:min => 1, :max => 10, :class=>"span1"}
        .span2= f.input :pubyear, :input_html=>{:min => 1900, :max => 2100, :class=>"span1"}
        .span4= f.input :edition, :input_html=>{:class=>"span4"}

      .row
        .span3= f.input :collation
        .span3= f.input :isbn
        .span3= f.input :isbn13

      .row
        .span2= f.input :call1, :placeholder => "QA", :input_html=>{:class=>"span2"}
        .span2= f.input :call2, :placeholder => "268", :input_html=>{:class=>"span2"}
        .span2= f.input :call3, :placeholder => ".R53", :input_html=>{:class=>"span2"}
        .span2= f.input :call4, :placeholder => "2008", :input_html=>{:class=>"span2"}

      .row
        .span5= f.input :collection, :input_html=>{:class=>"span5"}
        -# .span5= f.input :publisher_name, :url => autocomplete_publisher_name_adm_books_path, :as => :autocomplete, :input_html=>{:class=>"span5"}
        .span5= f.input :publisher_name, :input_html=>{:class=>"span5"}

      .tabbable
        %ul.nav.nav-tabs
          %li
            %a{:href=>"#abstab", "data-toggle" => "tab"} Abstract
          %li
            %a{:href=>"#idxtab", "data-toggle" => "tab"} Index
          %li
            %a{:href=>"#toctab", "data-toggle" => "tab"} TOC
          %li.active
            %a{:href=>"#nottab", "data-toggle" => "tab"} Notes
      .tab-content
        .tab-pane.active{:id=>"abstab"}
          =f.input :abstract, :label=>false,:input_html=>{:class=>"span10"}
        .tab-pane{:id=>"idxtab"}
          =f.input :idx, :label=>false, :input_html=>{:class=>"span10"}
        .tab-pane{:id=>"toctab"}
          =f.input :toc, :label=>false, :input_html=>{:class=>"span10"}
        .tab-pane{:id=>"nottab"}
          =f.input :notes, :label=>false, :input_html=>{:class=>"span10"}
      -# if @book.new_record?
        = f.simple_fields_for :item do |item_form|
          .row
            .span4
              = item_form.association :lab, :collection => @labs, :label_method => lambda { |l| l.nick }, :prompt => "Select the owner"
            .span4
              = item_form.association :location, :collection => @locations, :prompt => "Select a room for this copy"
          .row
            .span4
              = item_form.input :currency, :collection=>@currencies, :selected => @currencies.first
            .span4
              = item_form.input :price
          = f.input :status, :collection=>["Library", "Mystery", "Never Received", "Out of Print", "Waiting for Delivery"], :selected=>"Library"


  .form-actions
    = f.button :submit

app/views/adm/books/create.html.haml
-content_for(:title) do
  Books
  - if @isbn
    %br
    %small with ISBN = #{@isbn}

%p
  More than one book with ISBN #{@isbn} was found. Please select the one your want and then add a new item to it.
- if @deg_isbn
  %p
    Even better, help cleaning up our database by
    =link_to "merging", edit_adm_deg_isbn_path(@deg_isbn)
    the books into a single record.

= render :partial => "books/books"

app/views/adm/books/duplicate.html.haml
-content_for(:title) do
  Edit a Book duplicate
  %small
    ISBN:
    =@book.isbn

= simple_form_for([:adm, @book]) do |f|
  = f.error_notification

  .form-inputs
    .row
      .span1= f.input :volume, :input_html=>{:min => 1, :max => 10, :class=>"span1"}
      .span2= f.input :pubyear, :input_html=>{:min => 1900, :max => 2100, :class=>"span1"}
      .span4= f.input :edition, :input_html=>{:class=>"span4"}

    =f.input :notes, :label=>false, :input_html=>{:class=>"span10"}

  .form-actions
    = f.button :submit

app/views/adm/books/edit.html.haml
-content_for(:title) do
  Edit book.
  %small
    ISBN:
    =@book.isbn

-# TODO show this only if user can add books
%p
  \... or
  = link_to 'add an item', new_adm_book_item_path(@book)
  to this book or
  =link_to 'duplicate it', adm_book_duplicate_path(@book)
  \.

= render 'form'

= link_to 'Show', adm_book_path(@book)
\|
= link_to 'Back', :back

app/views/adm/books/new.html.haml
-content_for(:title) do
  New Book
  %small
    \-
    - if @isbn_step
      step 1
    - else
      step 2
= render 'form'

= link_to 'Back', :back

app/views/adm/books/new_as_merge.html.haml
-content_for(:title) do
  New Book

%p
  Please fill the form below and submit to create a new book.
%p
  To avoid typing, you can also use the data from the books shown here
  are taken from the web (google and/or library of congress).

#merger{:data=>{"no-turbolink"=>true}}

  = simple_form_for([:adm, @book]) do |ff|
    %ul.mergebooklist.unstyled
      -for i in (0...@books.count).step(2)
        .row
          .span6
            =render :partial=>"adm/deg_isbns/mergebook", :locals => {:b => @books[i]}
          - if @books[i+1]
            .span6
              =render :partial=>"adm/deg_isbns/mergebook", :locals => {:b => @books[i+1]}
    .form-actions
      = ff.button :submit, "Save"
    = simple_fields_for @book do |f|
      .form-inputs{:id => "mergeform"}
        = f.input :isbn, :as => :hidden, :value=>@book.isbn
        = f.input :author, :input_html=>{:class => "span10"}
        = f.input :title, :input_html=>{:class => "span10"}
        = f.input :editor, :input_html=>{:class => "span10"}
        .row
          .span1= f.input :volume, :input_html=>{:min => 1, :max => 10, :class=>"span1"}
          .span2= f.input :pubyear, :input_html=>{:min => 1900, :max => 2100, :class=>"span1"}
          .span4= f.input :edition, :input_html=>{:class=>"span4"}

        .row
          .span3= f.input :collation
          .span2= f.input :call1, :input_html=>{:class=>"span2"}
          .span2= f.input :call2, :input_html=>{:class=>"span2"}
          .span2= f.input :call3, :input_html=>{:class=>"span2"}
          .span2= f.input :call4, :input_html=>{:class=>"span2"}

        .row
          .span4= f.input :collection, :input_html=>{:class=>"span4"}
          -#.span8= f.input :publisher_name, :url => autocomplete_publisher_name_adm_books_path, :as => :autocomplete, :input_html=>{:class=>"span4"}
          .span8= f.input :publisher_name, :input_html=>{:class=>"span4"}

        .tabbable
          %ul.nav.nav-tabs
            %li
              %a{:href=>"#abstab", "data-toggle" => "tab"} Abstract
            %li
              %a{:href=>"#idxtab", "data-toggle" => "tab"} Index
            %li
              %a{:href=>"#toctab", "data-toggle" => "tab"} TOC
            %li.active
              %a{:href=>"#nottab", "data-toggle" => "tab"} Notes
        .tab-content
          .tab-pane.active{:id=>"abstab"}
            =f.input :abstract, :label=>false, :as => :text, :input_html=>{:class=>"span12"}
          .tab-pane{:id=>"idxtab"}
            =f.input :idx, :label=>false, :as => :text, :input_html=>{:class=>"span12"}
          .tab-pane{:id=>"toctab"}
            =f.input :toc, :label=>false, :as => :text, :input_html=>{:class=>"span12"}
          .tab-pane{:id=>"nottab"}
            =f.input :notes, :label=>false, :as => :text, :input_html=>{:class=>"span12"}