config/routes.rb
Thot::Application.routes.draw do

  resources :books, :only => [:index, :show]
  resources :items, :only=>[:show]
  resources :loans, :only => [:create, :destroy]
  resources :publishers, :only => [:show]
  resources :searches
  resources :shelves, :only => [:show] do
    resources :items, :only => [:index]
  end

  resources :users, :only => [:show, :index]
  namespace :nebis do
    get 'extend'
  end
  resources :nebis, :only => [:show]

  devise_for :admins
  namespace :adm do
    resources :admins do
      get :reset_password
    end
    resources :books do
      get :autocomplete_publisher_name, :on => :collection
      get :duplicate
      resources :items, :only=>[:new, :create]
    end
    resources :deg_isbns do
      get :skip, :on => :member
    end
    resources :goods
    resources :inventory_sessions do
      resources :shelves, :only => [:show]
      post :check
      post :uncheck
      get  :commit_moves
      get  :commit_missings
    end
    match 'inventory_sessions/inventorize_search', :to => 'inventory_sessions#inventorize_search', :via => :post, :as => 'inventorize_search'
    resources :items, :only=>[:index, :show, :edit, :update, :destroy]
    resources :labs
    resources :locations do
      resources :shelves, :only=>[:new, :create, :index]
    end
    resources :label_layouts
    resources :publishers, :only => [:index, :new, :edit, :create, :update, :destroy]
    resources :publisher_mergers, :only=>[:new, :create, :update]
    resources :shelves, :only => [:index, :show, :update, :destroy]
    resources :users do
    end
  end

  root :to => "searches#new"

end

app/models/search.rb
class Search < ActiveRecord::Base
  belongs_to :lab
  belongs_to :location

  validates_format_of :inv_range, with: /(^\s*[0-9]+\s*$)|(^\s*[0-9]+\s*((\.\.|-)\s*[0-9]+)?\s*$)|(^\s*[0-9]+(\s*,s*[0-9]+)*\s*$)/,
    message: "Format for range: N or N1..N2 or N1-N2 or N1,N2,N3 (where N is a number)", allow_nil: true, allow_blank: true

  def items
    raise "Please call search before fetching result" unless @search_called
    @items ||= items_oriented? ? @entries : items_from_books
  end

  def books
    raise "Please call search before fetching result" unless @search_called
    @books ||= items_oriented? ? books_from_items : @entries
  end

  # pagination shortcuts
  def per_page
    (@entries.nil? || @entries.empty?) ? 50 : @entries.per_page
  end

  def current_page
    (@entries.nil? || @entries.empty?) ? 0 : @entries.current_page
  end

  def next_page
    (@entries.nil? || @entries.empty?) ? 1 : @entries.next_page
  end

  def total_entries
    (@entries.nil? || @entries.empty?) ? 0 : @entries.total_entries
  end

  def total_pages
    (@entries.nil? || @entries.empty?) ? 0 : @entries.total_pages
  end

  def size
    (@entries.nil? || @entries.empty?) ? 0 : @entries.size
  end

  # def inventory_session
  #   nil
  # end

  # def inventory_session_id
  #   nil
  # end

  # def inventory_session=(is)
  #   puts "Should add search results to InventorySession #{is.name}"
  # end

  # def inventory_session_id=(is_id)
  #   is = InventorySession.find(is.id)
  #   inventory_session = is
  # end

  def search(params={})
    paginate_params = {:per_page => params[:per_page] || per_page, :page => params[:page] || next_page}

    order_book="title ASC"
    order_item="id DESC"
    # if params[:item_order_by]

    # end

    @entries=nil
    @items=nil
    @book=nil
    @items_oriented = nil
    @search_called = true

    # single inventory number
    if !inv_range.blank? && (i=parse_range(inv_range)).is_a?(Integer)
      inv=i # inv_range.strip.to_i
      logger.debug "Simple search for inv=#{inv}"
      @entries = Item.where(:id=>inv).order(order_item).paginate(paginate_params)
      @items_oriented = true
      return
    end

    # bookle isbn
    unless isbn.blank?
      @entries = Book.where(:isbn => isbn).paginate(paginate_params)
      @items_oriented = false
      logger.debug "Simple search for isbn=#{isbn}"
      return
    end

    # # if query is present we use search (sphinx) otherwise we use standard SQL
    # if item_conds.empty? && book_conds.empty? && query.blank?
    # end

    if query.blank?
      if item_conds.empty? && book_conds.empty?
        @entries = []
        return
      end
      if book_conds.empty?
        logger.debug("SQL    search only on items: item_conds=#{item_conds.inspect}")
        if params[:items_only]
          @entries = Item.where(item_conds).paginate(paginate_params)
        else
          @entries = Item.includes(:inventoriable).where(item_conds).paginate(paginate_params)
        end
        @items_oriented = true
      else
        logger.debug("SQL    search: book_conds=#{book_conds.inspect}\n               item_conds=#{item_conds.inspect}")
        conditions=book_conds
        conditions[:items] = item_conds
        @entries = Book.includes(:items).where(conditions).paginate(paginate_params)
        @items_oriented = false
      end
    else
      conditions=book_conds.merge(item_conds)
      if !inv_range.blank? || !inv_date_fr.blank? || !inv_date_to.blank? || !lab_id.blank? || !location_id.blank? || !status.blank?
        logger.debug("Sphinx search on item: query=#{query}\n               conds=#{conditions.inspect}")
        @entries = Item.search(query, {:with=>conditions}.merge(paginate_params))
        @items_oriented = true
      else
        logger.debug("Sphinx search on book: query=#{query}\n               conds=#{conditions.inspect}")
        @entries = Book.search(query, {:with=>conditions}.merge(paginate_params))
        @items_oriented = false
      end
    end
  end

  def publisher_ids
    @publisher_ids ||= publisher_ids_from_name(publisher_name)
  end

  def items_oriented?
    @items_oriented
  end

  def simple_query?
    nba=attributes.select{|k,v| !v.blank?}
    !query.blank? && nba.size==1
  end

  def inv_number
    return @inv_number if @inv_number
    @inv_number = if inv_range.blank?
      -1
    else
      r=parse_range(inv_range)
      r.is_a?(Integer) ? r : -1
    end
  end

 # private

  # conditions for books
  def book_conds
    unless @book_conds
      @book_conds={}
      unless publisher_ids.empty?
        @book_conds[:publisher_id] = publisher_ids
      end
      unless year_range.blank?
        @book_conds[:pubyear] = parse_range(year_range)
      end
    end
    @book_conds
  end

  # conditions for items
  def item_conds
    unless @item_conds
      @item_conds = {}
      unless inv_range.blank?
        @item_conds[:id] = parse_range(inv_range)
      end
      unless lab_id.blank?
        @item_conds[:lab_id] = lab_id
      end
      unless location_id.blank?
        @item_conds[:location_id] = location_id
      end
      unless status.blank?
        @item_conds[:status] = status.strip
      end
      unless inv_date_to.blank? && inv_date_fr.blank?
        fr = inv_date_fr.blank? ? Date.new(1970) : inv_date_fr  # .to_date not necessary because converted automatically
        to = inv_date_to.blank? ? Date.tomorrow : inv_date_to
        @item_conds[:created_at] =  fr..to
      end
    end
    @item_conds
  end

  def publisher_ids_from_name(n)
    return [] if n.blank?
    # r=Publisher.where(:name => publisher_name)
    # if r.empty?
      r=Publisher.where("LOWER(name) LIKE ?", "%#{n.downcase}%")
    # end
    r.empty? ? [] : r.map{|p| p.id}
  end

  def books_from_items
    # puts "books_from_items"
    return [] if @entries.nil? || @entries.empty?
    # @items.map{|i| i.book}.uniq
    ids = items.map{|i| i.inventoriable_id}
    Book.find(ids)
  end

  def items_from_books
    # puts "items_from_books"
    return [] if @entries.nil? || @entries.empty?
    i=[]
    books.each {|b| i += b.items}
    return i
  end


  def parse_range(y)
    ys=y.strip
    if ys.index("..")
      f,t=ys.split("..").each{|v| v.strip.to_i}
      return f..t
    elsif ys.index("-")
      f,t=ys.split("-").each{|v| v.strip.to_i}
      return f..t
    elsif ys.index(",")
      return ys.split(",").map{|y| y.strip.to_i}
    elsif ys =~ /^\s*[0-9]+\s*/
      return ys.to_i
    end
  end

  def find_books
    Product.find(:all, :conditions => book_conditions)
  end

  def find_items
    Product.find(:all, :conditions => item_conditions)
  end

  def title_book_conditions
    ["books.title LIKE ?", "%#{title}%"] unless title.blank?
  end

  def author_book_conditions
    ["books.title LIKE ?", "%#{title}%"] unless title.blank?
  end

  # def keyword_conditions
  #   ["products.name LIKE ?", "%#{keywords}%"] unless keywords.blank?
  # end

  # def minimum_price_conditions
  #   ["products.price >= ?", minimum_price] unless minimum_price.blank?
  # end

  # def maximum_price_conditions
  #   ["products.price <= ?", maximum_price] unless maximum_price.blank?
  # end

  # def category_conditions
  #   ["products.category_id = ?", category_id] unless category_id.blank?
  # end

  def book_conditions
    [book_conditions_clauses.join(' AND '), *conditions_options]
  end

  def book_conditions_clauses
    conditions_parts.map { |condition| condition.first }
  end

  def book_conditions_options
    book_conditions_parts.map { |condition| condition[1..-1] }.flatten
  end

  def book_conditions_parts
    private_methods(false).grep(/_book_conditions$/).map { |m| send(m) }.compact
  end

  def item_conditions
    [item_conditions_clauses.join(' AND '), *conditions_options]
  end

  def item_conditions_clauses
    conditions_parts.map { |condition| condition.first }
  end

  def item_conditions_options
    book_conditions_parts.map { |condition| condition[1..-1] }.flatten
  end

  def item_conditions_parts
    private_methods(false).grep(/_item_conditions$/).map { |m| send(m) }.compact
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # TODO: re-enable autocomplete when a rails4 compatible version is out
  # autocomplete :publisher, :name, :full => true

  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @searches }
    end
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
    @search = Search.find(params[:id])
    perpage = request.format == 'pdf' ? 999 : 48
    @search.search(page: params[:page], :per_page => perpage)
    if @search.total_entries == 1
      @entry = @search.items_oriented? ? @search.items.first : @search.books.first
    end
    respond_to do |format|
      format.pdf  { @items = @search.items ; render 'items/index' }
      format.html do
        redirect_to @entry unless @entry.nil?
        # show.html.erb
      end
    end
  end

  # GET /searches/new
  # GET /searches/new.json
  def new
    gon.root = true
    @search = Search.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @search }
    end
  end

  # GET /searches/1/edit
  def edit
    @search = Search.find(params[:id])
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)
    if @search.simple_query?
      redirect_to books_path(:search=>@search.query)
    elsif @search.inv_number > 0
      redirect_to item_path(@search.inv_number)
    else
      respond_to do |format|
        if @search.save
          format.html { redirect_to @search, notice: 'Search was successfully created.' }
          format.json { render json: @search, status: :created, location: @search }
        else
          format.html { render action: "new" }
          format.json { render json: @search.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /searches/1
  # PUT /searches/1.json
  def update
    @search = Search.find(params[:id])

    respond_to do |format|
      if @search.update_attributes(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search = Search.find(params[:id])
    @search.destroy

    respond_to do |format|
      format.html { redirect_to searches_url }
      format.json { head :no_content }
    end
  end

 private

  def search_params
    if admin_signed_in?
      params.require(:search).permit(:query, :isbn, :publisher_name, :year_range, :inv_range, :lab_id, :location_id, :status, :inv_date_fr, :inv_date_to)
    else
      params.require(:search).permit(:query, :isbn, :publisher_name, :year_range, :inv_range, :lab_id, :location_id)
    end
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.haml
= simple_form_for @search do |f|
  = f.error_notification

  .form-inputs
    .row
      .span6= f.input :query, :label=>"Title, author or editor", :input_html => {:class => "span6"}
      .span3= f.association :lab, :label_method => lambda { |l| l.nick }, :label => "Owner Lab", :prompt => "Select a Lab", :input_html => {:class => "span3"}
      .span3= f.association :location, :collection => Location.order('Name ASC'), :label => "Room", :prompt => "Select a Room", :input_html => {:class => "span3"}
    .row
      .span3= f.input :isbn, :input_html => {:class => "span3"}
      .span3= f.input :publisher_name, :input_html => {:class => "span3"}
      .span3= f.input :year_range, :label=>"An year, list of years or range", :placeholder=>"'2001' or '2001-2005' or '2001, 2004, 2007'", :input_html => {:class => "span3"}
      .span3= f.input :inv_range, :label => "Inventory number, range or list", :placeholder => "123 or 123-166 or 123,125,189"
    .row
      - if admin_signed_in?
        -#.span3= f.input :inv_range, :label => "Inventory number, range or list", :placeholder => "123 or 123-166 or 123,125,189"
        .span3= f.input :inv_date_fr, :label => "Inventory created from", :as => :date_picker
        .span3= f.input :inv_date_to, :label => "Inventory created to", :as => :date_picker
        .span3= f.input :status, :collection => Item.statuses, :prompt => "Select a Status"
  .form-actions
    .row
      .span10
        = f.button :submit, "Go Search!"
      .span2
      = link_to "reset form", new_search_path

app/views/searches/edit.html.haml
%h1 Editing search

= render 'form'

= link_to 'Show', @search
\|
= link_to 'Back', searches_path

app/views/searches/index.html.haml
%h1 Listing searches

%table
  %tr
    %th Title
    %th Author
    %th Editor
    %th Isbn
    %th Year
    %th Publisher name
    %th Collection
    %th Location
    %th Owner
    %th Status
    %th User
    %th
    %th
    %th

  - @searches.each do |search|
    %tr
      %td= search.title
      %td= search.author
      %td= search.editor
      %td= search.isbn
      %td= search.year
      %td= search.publisher_name
      %td= search.collection
      %td= search.location_id
      %td= search.owner_id
      %td= search.status
      %td= search.user_id
      %td= link_to 'Show', search
      %td= link_to 'Edit', edit_search_path(search)
      %td= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Search', new_search_path

app/views/searches/new.html.haml
%h1 Search

= render 'form'

.alert.alert-info.alert-block
  %h1 Thot reloaded
  %p
    Dear library administrator/operator, as you can see, we have rewritten the glorious Thot library system.
  %p
    Please
    =link_to "contact the administrator", "mailto:#{ENV['ADMIN_EMAIL']}"
    in order to obtain a new valid operator account. Thank you!

app/views/searches/show.html.haml
-content_for(:title) do
  Search Result
  %br
  %small #{@search.total_entries} items found

%h2 Your search
= render 'form'

- if @search.total_entries > 0
  - if admin_signed_in?
    .row
      .span5
        %h4 Labels
        %p=print_labels_links(search_path(@search))
      - if @search.items_oriented?
        .span7
          %h4 Inventorize
          - if current_admin.inventory_sessions.count > 0
            %p
              To add all the items of this search (search no. #{@search.id}) to an inventory session, please select your inventory session below and submit.
              Items that are already present in the inventory session will be considered as not yet checked (reset).
            %p
              Searches containing a lot of items
              %strong could take long time to load
              and your browser might look unresponsive for a while.
            = simple_form_for(:inventorize, url: adm_inventorize_search_url, :method => :post) do |f|
              = f.hidden_field "search_id", :value => @search.id
              .row
                .span3
                  = f.input "session_id", :collection => current_admin.inventory_sessions, :label_method => lambda { |s| s.name}, :label=>false, :include_blank => false #, :selected =>  current_admin.inventory_sessions[0]
                  -#= f.error  :session_id
                .span2
                  = f.button :submit, "Inventorize"
          - else
            %p
              In order to setup an inventory session for the items in this search, please
              =link_to "create a new inventory session", new_adm_inventory_session_path
              first.
  %h3
    = @search.items_oriented? ? "Items" : "Books"
  %p
    Found #{@search.total_entries} entries.
    - if @search.total_pages > 1
      Showing #{@search.size} entries (page #{@search.current_page} of #{@search.total_pages})
  - if @search.items_oriented?
    %ul.booklist.unstyled
      = render partial: "items/item", collection: @search.items
  -else
    %ul.booklist.unstyled
      =render partial: "books/book", collection: @search.books

  = might_paginate @search
- else
  %p
    no results to show.